### ISSUE TITLE
TODO: Making rotation permanent

### ISSUE THREAD

**Issue by thopiekar** [thopiekar/CuraSolidWorksPlugin#20]
For a reason, it is not trivial to make the rotation permanent.

TODO:
 - [x] Get in contact with someone at the Cura team or software department to understand how it comes.
 - [x] Working out a functional solution
 - [x] Fixing the lines of code in the post-processing function
