### ISSUE TITLE
TODO: Shrinking the macro

### ISSUE THREAD

**Issue by thopiekar** [thopiekar/CuraSolidWorksPlugin#33]
Definitely the macro needs a major shrinkage.

TODO:
- [x] Keep the bits of code, which are checking for the Cura installation
- [x] SiemensNX plugin has some functions to do that
  - [x] Check and see whether they are better or not
  - [x] Getting out the cherries
  - [x] Bundling also everything into a function to improve readability
- [x] Removing the code, which is doing a conversion and a exporting into an STL.
- [x] Passing directly the so called "active document" to Cura directly.
  - The plugin itself determines the filepath. We can get inspiration from here.

**Comment by thopiekar** [comment]
With help of @Appesteijn this has been fixed.
Thanks again!
