### ISSUE TITLE
TODO: Letting the user know, why the plugin is not running.

### ISSUE THREAD

**Issue by thopiekar** [thopiekar/CuraSolidWorksPlugin#34]
There are several cases, where the plugin can't be used. We should let the user know why the plugin is not appearing.

Undecided: Disabling the plugin when not running under Windows or SolidWorks can't be found.

TODO:
 - [x] On detection of an OS != Windows
   - [x] Kindly tell the user that this OS is not supported.
 - [x] If there is no valid SolidWorks installation (Only show if there is none working)
   - [x] Tell that SolidWorks is needed for this plugin to run.  (If no registry key has been found)
   - [x] If the installation is not passing our checks, tell the user to contact their ICT. (orphaned registry keys)
   - [ ] If the licence can't be obtained, tell the user to care about getting an valid licence.
 - [x] If there is one working, but some not, give the user a summary of what is happening.
   - [x] Collect all info on a tabbed page in the plugin settings or create a new entry in the menu. All points shall be visible with a ✔️ or a ❌. 
   - [x] By hovering the text there shall be an technical explaination for the local ICT, why things are failing. Not meant to be read by the mechanical engineer.

**Comment by thopiekar** [comment]
Moving the details to 0.5.0.
