### ISSUE TITLE
TODO: Quality fallback mechanism

### ISSUE THREAD

**Issue by thopiekar** [thopiekar/CuraSolidWorksPlugin#5]
Heard that it can sometimes fail to export in fine quality. (got this from @nallath )

TODO:
- [x] Need to ask DS how does it come.
- [x] Ask DS for a test case.. a part or assembly
- [x] Implementing the fallback, but keeping in mind we want own quaility profiles and allow users to set their custom one.

**Comment by thopiekar** [comment]
Implemented in CadIntegrationUtils and email sent
